const NOTIFICATION_TYPES = {
  AUCTION_WON: 'AUCTION_WON',
  AUCTION_LOST: 'AUCTION_LOST',
  AUCTION_ENDED: 'AUCTION_ENDED',
  AUCTION_UNSOLD: 'AUCTION_UNSOLD',
};

module.exports = { NOTIFICATION_TYPES };