import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import SellerWorkspace from '../components/SellerWorkspace';
import { getCategories } from '../api/categoriesApi';
import { createProduct } from '../api/productsApi';
import { useToast } from '../components/toastContext';
import styles from './SellerPages.module.css';

const initialForm = { title: '', category_id: '', condition: 'USED', description: '', primary_image: '', additional_images: [''] };

export default function SellerProductCreatePage() {
  const navigate = useNavigate();
  const showToast = useToast();
  const [categories, setCategories] = useState([]);
  const [form, setForm] = useState(initialForm);
  const [specifications, setSpecifications] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => { let isCurrent = true; getCategories().then((result) => { if (!isCurrent) return; setCategories(result); setForm((previous) => ({ ...previous, category_id: result[0]?.id || '' })); }).catch((error) => isCurrent && showToast(error.message || 'Unable to load categories.')).finally(() => isCurrent && setIsLoading(false)); return () => { isCurrent = false; }; }, [showToast]);
  const changeImage = (index, value) => setForm((previous) => ({ ...previous, additional_images: previous.additional_images.map((image, imageIndex) => imageIndex === index ? value : image) }));
  const removeImage = (index) => setForm((previous) => ({ ...previous, additional_images: previous.additional_images.filter((_, imageIndex) => imageIndex !== index) }));
  const submit = async (event) => { event.preventDefault(); if (specifications.some((specification) => !specification.key.trim() || !specification.value.trim())) { showToast('Complete or remove every specification row.'); return; } setIsSaving(true); try { await createProduct({ ...form, description: form.description || undefined, additional_images: form.additional_images.map((image) => image.trim()).filter(Boolean), detailed_specs: specifications.length ? Object.fromEntries(specifications.map((specification) => [specification.key.trim(), specification.value.trim()])) : undefined }); showToast('Product added to your inventory.', 'success'); navigate('/seller/products'); } catch (error) { showToast(error.message || 'Unable to add product.'); } finally { setIsSaving(false); } };
  return <SellerWorkspace title="Add product" eyebrow="NEW INVENTORY">{isLoading ? <div className={styles.loader}><i />Loading product form...</div> : <form className={styles.form} onSubmit={submit}><label>Product title<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="e.g. Hand-thrown ceramic vase" required /></label><label>Category<select value={form.category_id} onChange={(event) => setForm({ ...form, category_id: event.target.value })} required>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Condition<select value={form.condition} onChange={(event) => setForm({ ...form, condition: event.target.value })}><option>NEW</option><option>USED</option><option>REFURBISHED</option></select></label><label>Primary image URL<input type="url" value={form.primary_image} onChange={(event) => setForm({ ...form, primary_image: event.target.value })} required /></label><label className={styles.full}>Description<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} rows="4" placeholder="Condition, provenance, and included details" /></label><div className={`${styles.full} ${styles.imageRows}`}><label>Additional image URLs</label>{form.additional_images.map((image, index) => <div className={styles.imageRow} key={index}><input type="url" value={image} onChange={(event) => changeImage(index, event.target.value)} placeholder="https://example.com/detail.jpg" />{form.additional_images.length > 1 ? <button className={styles.removeRow} type="button" onClick={() => removeImage(index)}>Remove</button> : null}</div>)}<button className={`btn-outline ${styles.addRow}`} type="button" onClick={() => setForm((previous) => ({ ...previous, additional_images: [...previous.additional_images, ''] }))}>Add image</button></div><div className={styles.full}><label>Detailed specifications</label>{specifications.map((specification, index) => <div className={styles.specRow} key={index}><input value={specification.key} onChange={(event) => setSpecifications((previous) => previous.map((item, itemIndex) => itemIndex === index ? { ...item, key: event.target.value } : item))} placeholder="Specification" /><input value={specification.value} onChange={(event) => setSpecifications((previous) => previous.map((item, itemIndex) => itemIndex === index ? { ...item, value: event.target.value } : item))} placeholder="Value" /><button type="button" onClick={() => setSpecifications((previous) => previous.filter((_, itemIndex) => itemIndex !== index))}>Remove</button></div>)}<button className="btn-outline" type="button" onClick={() => setSpecifications((previous) => [...previous, { key: '', value: '' }])}>Add specification</button></div><button className="btn-primary" type="submit" disabled={isSaving}>{isSaving ? 'Adding product...' : 'Add product'}</button></form>}</SellerWorkspace>;
}