const AUCTION_CANCELLATION_WINDOW_MS = 5 * 60 * 1000;
const AUCTION_LIFECYCLE_CRON_SCHEDULE = '* * * * *';

const ACCESS_TOKEN_EXPIRES_IN = '24h';
const ACCESS_TOKEN_COOKIE_MAX_AGE_MS = 24 * 60 * 60 * 1000;
const REFRESH_TOKEN_EXPIRES_IN_DAYS = 7;
const REFRESH_TOKEN_COOKIE_MAX_AGE_MS = REFRESH_TOKEN_EXPIRES_IN_DAYS * 24 * 60 * 60 * 1000;

module.exports = {
  AUCTION_CANCELLATION_WINDOW_MS,
  AUCTION_LIFECYCLE_CRON_SCHEDULE,
  ACCESS_TOKEN_EXPIRES_IN,
  ACCESS_TOKEN_COOKIE_MAX_AGE_MS,
  REFRESH_TOKEN_EXPIRES_IN_DAYS,
  REFRESH_TOKEN_COOKIE_MAX_AGE_MS,
};